baseURL = "https://adrienoyono.fr"
title = "Morning Dew"
theme = "hugo-coder"
paginate = 5

buildFuture = true
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
enableRobotsTXT = true

newContentEditor = "emacsclient -t"
pluralizeListTitles = false
disqusShortname = "aoyono"

[params]
  description = "An african's mind"
  author = "Adrien Oyono"
  info = "Aerospace & Software engineer"
  keywords = "blog, engineering, python, developer, scientist, Africa, Cameroon"
  gravatar = "adrienoyono@gmail.com"

  footercontent = "All rights reserved"

  hidecredits = false
  hidecopyright = false
  since = 2018

  rtl = false
  math = true

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  colorscheme = "auto"
  maxSeeAlsoItems = 3

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"


[markup]
  [markup.highlight]
    style = "solarized-dark"


[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Blog"
    weight = 2
    url = "posts/"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/aoyono/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/onoyoyono/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/adrienoyono/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram"
    weight = 5
    url = "https://www.instagram.com/oyononoyo/"

[permalinks]
  posts = "/posts/:year/:month/:title/"