#+TITLE: Ma rencontre avec Schopenhauer
#+DATE: 2018-05-09
#+TAGS[]: philosophie lecture
#+STATUS: published


Quelque  chose m'a  fait  trainer  mon corps  à  la fnac  la
semaine dernière  (Jeudi 3  mai 2018),  à la  recherche d'un
cadeau  pour  ma  bien  aimée.  Je  suis  tombé  sur  Arthur
Schopenhauer à  la place:  "L'Art d'avoir  toujours raison",
suivi de 2 autres textes du  même auteur: "La lecture et les
livres"  et "Le  penseur  personnel". 3  textes courts  mais
lourds de conséquences pour moi.


* Avoir toujours raison


Dans  le premier,  l'auteur donne  une liste  de stratagèmes
(environ 35)  pour mener et  gagner un débat.   J'y apprends
qu'Aristote a des écrits sur  le sujet: "Les Topiques".  Ces
Topiques  se  rajoutent  donc  à la  liste  des  lectures  à
absolument faire, moi qui  presque toujours peine à acquerir
à ma  cause le  maigre public qui  assiste à  quelques rares
occasions où  j'ai eu à  débattre avec des personnes  de mon
entourage.


* Le lecteur frénétique

La lecture, c'est de ça qu'il est justement question dans le
texte  de  Schopenhauer  qui  suit  l'Art  d'avoir  toujours
raison.  L'auteur  y  émet quelques  thèses  (auxquelles  je
pouvais  en  quelque sorte  m'attendre)  qui  me poussent  à
penser que  je devrais reffreiner  ma propension à  lire les
textes d'autres penseurs. Par exemple, il émet l'opinion que
lire quelqu'un, c'est  quasiment rentrer dans la  tête de ce
dernier, et  donc penser comme  lui, ou du moins  essayer de
penser comme  lui, ou encore  suivre les "traces de  ses pas
dans  la neige,  montrant le  chemin qu'il  a emprunté  pour
arriver à  une certaine connaissance", mais,  ce faisant, on
ne peut pas voir la même chose que lui simplement en suivant
ses pas, il faut se servir  de ses propres yeux pour essayer
de voir  ce qu'il a vu.   Tout ceci pour signifier  qu'il ne
faut pas se  contenter de faire une foule  de lectures, mais
il faut  encore excercer sa  propre pensée entre  2 lectures
afin de ne pas complètement noyer la pensée critique dans la
foule  d'idées  reçues de  l'extérieur  qui  s'opère par  la
lecture.  L'auteur  conseille également  de ne lire  que les
bons penseurs, dont la  grandeur d'esprit ne souffre d'aucun
doute ou presque. Il  faudrait donc accorder de l'importance
aux grands  penseurs de chaque époque,  depuis "Les Anciens"
grecs, jusqu'aux  auteurs les  plus contemporains,  en ayant
une préférence pour les auteurs contemporains qui ne pondent
pas nécessairement un  nouveau livre tous les  4 matins pour
le simple besoin du commerce,  car les moins médiatisés sont
souvent les plus bons.  Il se  pose avec cela la question de
comment identifier les bons auteurs  des mauvais ? C'est une
question à laquelle je devrai répondre moi même, en tant que
partie intégrante de mon processus de formation d'un système
pensées bien à moi, processus  qui m'a été comme "dicté" par
la  lecture   du  dernier   texte  du  livre:   "Le  penseur
personnel".


* Le penseur

Dans ce dernier texte, Schopenhauer souligne l'importance de
posséder justement  son propre système de  pensées, afin que
le  "moi pensant"  ne  se  fasse pas  éclipser  par le  "moi
paresseux" se reposant entièrement  sur les idées d'un autre
"moi pensant", extérieur au  moi personnel, phénomène qui se
produit quand on  se laisse aller à la  lecture gloutonne et
effrénée non entrecoupée de  pauses visant l'assimilation de
ce qu'on a lu et la  comparaison avec son système de pensées
personnelles.

Ma  rencontre  avec  Schopenhauer   s'achève  donc  par  une
résolution à  former pour mon  propre compte mon  système de
pensées, et ce  en m'exerçant régulièrement à  examiner et à
approfondir mes pensées. Il est vrai qu'il y en a bon nombre
qui  me  viennent  souvent  à l'esprit,  et  que  je  laisse
régulièrement filer  sans chercher  à les systématiser  et à
les  mettre  sur écrit  pour  en  examiner l'essence  et  la
portée.   Je m'engage  donc  à la  sortie  de cette  lecture
courte mais  ô combien  importante, à  former ce  système de
pensées.  Celà commencera par une tentative de définition de
ce qu'est au juste un système de pensées.


* Qu'est-ce qu'un système de pensées?


La première chose  qui me vient à l'esprit quand  je me pose
cette  question  c'est:  un ensemble  structuré  de  pensées
portant sur un domaine en  particulier ou sur un ensemble de
domaines,  formant un  tout compact  et indissociable.   Les
pensées qui  constituent ce système se  doivent d'être liées
d'une  façon  ou d'une  autre.   L'ensemble  doit avoir  une
cohérence.  En  définitive, je peux même  dire qu'un système
de pensée est  une théorie au sens  "scientifique" du terme,
ce qui implique qu'il possède:

    - des  axiomes ou  prémisses, qui  sont des  éléments de
      bases dont la vérité est admise
    - des propositions  qui reposent  sur les  premisses, en
      sont des combinaisons en quelque sorte
    - des théorèmes qui constituent les thèses de la théorie
      ou du système de pensées, qui peuvent être démontrés à
      l'aide des prémisses et des propositions
    - des  corrollaires   qui  sont  les   conséquences  des
      théorèmes et des propositions


* Qu'est-ce qu'une pensée?


Mais j'y pense,  avant même de définir ce  qu'est un système
de pensées, suis-je certain d'avoir  même une idée de ce que
peut être son  unité fondamentale, j'ai nommé:  Une pensée ?
La réponse est non, alors je vais tenter une définition.

Une pensée,  c'est un mouvement  de l'esprit, un  passage de
l'état  d'inconscient à  l'état de  conscient d'une  vérité,
d'une réalité  ou de tout  autre élément matériel  ou idéel,
qui se manifeste  par une sorte de "voix" dans  la tête, qui
questionne ou qui affirme, ou alors fait les deux à la fois,
dans  un  ordre  quelconque.   Soit elle  affirme  avant  de
questionner, soit elle fait  l'inverse.  Il est difficile de
m'imaginer une  situation où elle  ferait les deux  de façon
simultanée.

Cette définition de la pensée  me permet donc de revenir sur
ma première définition de ce qu'est un système de pensées.

J'ai dit qu'une pensée est un mouvement, et qu'un système de
pensées est un ensemble de  pensées.  C'est donc un ensemble
de mouvements, et en définitive une dynamique.  Et puisqu'il
s'agit de  l'esprit humain, c'est une  dynamique de l'esprit
humain.  Une conséquence est donc que le fonctionnement d'un
esprit humain peut  être analysé par l'étude  de son système
de pensées.  En établissant  mon système de pensées, j'aurai
donc à  priori une chance  de savoir comment  fonctionne mon
esprit.


* Qu'est ce que l'esprit humain?


Mais quelque chose d'implicite s'est glissé dans tout ce que
je viens de dire.  En effet,  je semble supposer que je sais
ce que c'est qu'un esprit humain.  Non seulement ça, mais je
présuppose que l'esprit est quelque  chose qui peut avoir au
moins 2 états:  l'immobilité et la mouvance.   Dans son état
de mouvance, il génère une  ou plusieurs pensées.  Mais dans
ma définition de la pensée, celle-ci n'était qu'UN mouvement
(sous-entendu:  "parmi  tant  d'autres").   Je  laisse  donc
entendre  qu'il  pourrait  y avoir  d'autres  mouvements  de
l'esprit  qui ne  seraient pas  des pensées  ?  J'examinerai
plus tard cette question.  Pour l'instant, mes élucubrations
sur  l'esprit  me  semblent satisfaisantes,  j'accepte  donc
comme tel les sous entendus  et les pré-supposés que j'ai pu
faire.


* Une motivation pour le futur

Je  débouche au  final  sur une  motivation  pour créer  mon
système de pensées: étudier la dynamique de mon esprit.  Mon
systéme de pensées devra s'étaler sur toutes les disciplines
que je trouvent attrayantes: les mathématiques, la physique,
la philosophie, l'économie, la programmation, la société, la
nature.
